version: "3.7"

services:
#  rwe.api:
#    image: rwe.api
#    build:
#      context: .
#      dockerfile: ./rwe.api/Dockerfile
#    networks:
#      - rwe-net
#    ports:
#      - 5200:5200
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    volumes:
#      - ./rwe.api/log:/src/log

  rwe.worker:
    image: rwe.worker
    build:
      context: .
      dockerfile: ./rwe.worker/Dockerfile
    networks:
      - rwe-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./rwe.worker/log:/src/log

  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rwe-net
    environment:
      - RABBITMQ_DEFAULT_USER=rwe-rabbit-mq
      - RABBITMQ_DEFAULT_PASS=zJoh5SV6w66pe8%I
    volumes:
      - rabbitmq:/var/lib/rabbitmq

networks:
  rwe-net:
    name: rwe-net
    driver: "bridge"
    external: true

volumes:
  rabbitmq:
    driver: local